/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

/**
 *
 * @author Admin
 */
public class TruongDuy_BT extends javax.swing.JFrame {

    /**
     * Creates new form TruongDuy_BT
     */
    public TruongDuy_BT() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TF_122 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TF2_122 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TF3_122 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        BT1_122 = new javax.swing.JButton();
        BT2_122 = new javax.swing.JButton();
        BT3_122 = new javax.swing.JButton();
        BT4_122 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 0));

        jLabel1.setText("SỐ THỨ NHẤT :");
        jPanel1.add(jLabel1);
        jPanel1.add(TF_122);

        jLabel2.setText("SÔ THỨ HAI:");
        jPanel1.add(jLabel2);
        jPanel1.add(TF2_122);

        jLabel3.setText("KẾT QUẢ");
        jPanel1.add(jLabel3);
        jPanel1.add(TF3_122);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        BT1_122.setText("+");
        jPanel2.add(BT1_122, new java.awt.GridBagConstraints());

        BT2_122.setText("-");
        jPanel2.add(BT2_122, new java.awt.GridBagConstraints());

        BT3_122.setText("*");
        jPanel2.add(BT3_122, new java.awt.GridBagConstraints());

        BT4_122.setText("/");
        jPanel2.add(BT4_122, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TruongDuy_BT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TruongDuy_BT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TruongDuy_BT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TruongDuy_BT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TruongDuy_BT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT1_122;
    private javax.swing.JButton BT2_122;
    private javax.swing.JButton BT3_122;
    private javax.swing.JButton BT4_122;
    private javax.swing.JTextField TF2_122;
    private javax.swing.JTextField TF3_122;
    private javax.swing.JTextField TF_122;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
